@startmindmap ideal_software
* Ideal Software
    * Strategic Uniqueness / 戦略的独自性（唯一無二の価値）
        * Algorithm / アルゴリズム
        * Collaborative with Machines / 機械との協働
    * Predictable / 予測可能（持続発展の基盤）
        * Concept Based / 概念に基づく
        * Theoretical / 理論的
        * Deterministic / 決定論的
        * Moduled Responsibilities / モジュール化された責務
        * Common Framework / 共通構造
        * Flexible Adaptation / 柔軟な適合
        * Self Descriptive / 自己記述的
        * Secure / 安全
    * Performance / 性能
        * Simple / シンプル
        * Low Memory Usage / 低メモリ使用
@endmindmap
