@startuml gof_template_method

title GoF - Behaviour #10 - Template Method

interface AbstractClass {
    template_method()
    {abstract} primitive_operation1()
    {abstract} primitive_operation2()
}

class ConcreteClass {
    primitive_operation1()
    primitive_operation2()
}

AbstractClass <|.. ConcreteClass
@enduml
