@startuml gof_strategy

title GoF - Behaviour #09 - Strategy

Interface Strategy {
    algorithm_interface()
}

class ConcreteStrategyA {
    algorithm_interface()
}

class ConcreteStrategyB {
    algorithm_interface()
}

class ConcreteStrategyC {
    algorithm_interface()
}

Strategy <|.. ConcreteStrategyA
Strategy <|.. ConcreteStrategyB
Strategy <|.. ConcreteStrategyC

class Context {
    context_interface()
}

Context o-- Strategy : strategy

@enduml
