@startuml gof_interpreter

title GoF - Behavior #03 - Interpreter

class Context

interface AbstractExpression {
    +interpret(context)
}

class TerminalExpression {
    +interpret(context)
}

class NonterminalExpression {
    +interpret(context)
}

AbstractExpression <|.. TerminalExpression
AbstractExpression <|.. NonterminalExpression
NonterminalExpression o-- AbstractExpression
@enduml