@startuml gof_factory_method

title GoF - Creational #03 - Factory Method

interface Product

class ConcreteProduct

Product <|.. ConcreteProduct

interface Creator {
    +factory_method(): Product
}

class ConcreteCreator {
    +factory_method(): Product
}

Creator <|.. ConcreteCreator
ConcreteCreator ..> ConcreteProduct
@enduml