@startuml gof_command

title GoF - Behavior #02 - Command

class Receiver {
    +action()
}

interface Command {
    +execute()
}

class ConcreteCommand {
    -receiver: Receiver
    +state
    +execute()
}

Command <|.. ConcreteCommand

class Invoker {
    -command: Command
    +set_command(c: Command)
    +execute_command()
}

Invoker --> Command
ConcreteCommand --> Receiver

class Client {
    +main()
}

Client --> Receiver
Client ..> ConcreteCommand
@enduml
