@startuml gof_bridge
title GoF - Structure #02 - Bridge

interface Implementor {
    +operation_impl(): void
}

class ConcreteImplementorA {
    +operation_impl(): void
}

class ConcreteImplementorB {
    +operation_impl(): void
}

Implementor <|.. ConcreteImplementorA
Implementor <|.. ConcreteImplementorB

interface Abstraction {
    -implementor: Implementor
    +operation(): void
}

class RefinedAbstraction {
    +operation(): void
}

Abstraction <|.. RefinedAbstraction

Abstraction --> Implementor
@enduml