@startuml gof_prototype

title GoF - Creational #04 - Prototype

abstract class Prototype {
    +clone(): Prototype
}

class ConcretePrototype1 {
    +clone(): Prototype
}

class ConcretePrototype2 {
    +clone(): Prototype
}

Prototype <|-- ConcretePrototype1
Prototype <|-- ConcretePrototype2

@enduml
